export const ADD_TO_STORAGE = "ADD_TO_STORAGE"

export const REMOVE_FROM_STORAGE = "REMOVE_FROM_STORAGE"

export const UPDATE_COMPANY_INFO = 'UPDATE_COMPANY_INFO';
export const UPDATE_CLIENT_INFO = 'UPDATE_CLIENT_INFO';
